name: yt_tutorial_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1
  google_sign_in: ^4.5.5
  future_progress_dialog: ^0.1.1
  flushbar: ^1.10.4
  image_picker: ^0.6.7+14
  firebase_storage: ^5.0.1
  esys_flutter_share: ^1.0.2
  
  #url 
  url_launcher: ^5.7.10

  #Whatsapp Launcher
  flutter_open_whatsapp: ^0.1.2

  #Image Loader
  transparent_image: ^1.0.0

  #Carousal Slider
  carousel_slider: ^2.3.1

  #Carousal Slider2
  carousel_pro: ^1.0.0

  #Bottom NavBar
  persistent_bottom_nav_bar: ^2.1.0

  #TinderCard
  flutter_tindercard: ^0.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter





# For information on the genersic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/placeholder.jpg
    - assets/images/pro_pic_1.jpg
    - assets/images/wall1.jpg
    - assets/images/wall2.jpg
    - assets/images/wall3.jpg
    - assets/images/wall4.jpg
    - assets/images/wall5.jpg
    - assets/images/wall6.png
    - assets/images/wall7.png
    - assets/images/slider1.png
    - assets/images/slider2.png
    - assets/images/slider4.png
    - assets/images/slider5.png
    - assets/images/cat1.png
    - assets/images/cat2.png
    - assets/images/giftBox.png
    
    

    



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat Regular  
      fonts:
        - asset: assets/fonts/mt_r.ttf

    - family: Montserrat Medium  
      fonts:
        - asset: assets/fonts/mt_m.ttf    
    
    - family: Montserrat Bold  
      fonts:
        - asset: assets/fonts/mt_b.ttf
    
    - family: Roboto  
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    
    - family: Roboto Italic  
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf 
        
    - family: Roboto Thin  
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf 

    - family: Roboto Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf         
        
    - family: Roboto Medium 
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf 
        
    - family: Roboto Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf 
        
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
